blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.PostListView.as_view(), name='list'),
    path('blog_app/', include('blog_app.urls'), name='blog_app'),
]

blog_app/urls.py
from unicodedata import name
from django.urls import path, reverse
from . import views


app_name = 'blog_app'

urlpatterns = [
    path('register/', views.UserInfoCreateView.as_view(), name='register'),
    path('login/', views.UserAuthenticationView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('comment/<int:pk>', views.CommentCreateView.as_view(), name='comment'),
]

blog_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=256)
    post_content = models.TextField()
    date_published = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse('blog_app:detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='comments')
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    date_published = models.DateTimeField(auto_now_add=True)
    comment_content = models.TextField()

    def __str__(self) -> str:
        return self.post.title

    def get_absolute_url(self):
        return reverse('blog_app:detail', kwargs={'pk': self.post.pk})

blog_app/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email']

blog_app/views.py
from pyexpat import model
from statistics import mode
from django import template
from . import models, forms
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy

# Create your views here.


class PostListView(ListView):
    context_object_name = 'posts'
    model = models.Post


class PostDetailView(DetailView):
    model = models.Post
    context_object_name = 'post_detail'
    template_name = 'blog_app/post_detail.html'


class PostCreateView(CreateView):
    model = models.Post
    template_name = 'blog_app/post_create.html'
    success_url = reverse_lazy('list')
    fields = ['title', 'post_content']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PostUpdateView(UpdateView):
    context_object_name = 'post'
    model = models.Post
    template_name = 'blog_app/post_update.html'
    fields = ['title', 'post_content']


class PostDeleteView(DeleteView):
    model = models.Post
    success_url = reverse_lazy('list')
    template_name = 'blog_app/post_delete.html'

class CommentCreateView(CreateView):
    context_object_name = 'comment'
    model = models.Comment
    template_name = 'blog_app/comment_create.html'
    fields = ['comment_content']

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)

class UserInfoCreateView(CreateView):
    form_class = forms.UserRegisterForm
    success_url = reverse_lazy('list')
    template_name = 'blog_app/user_registration.html'


class UserAuthenticationView(LoginView):
    template_name = 'blog_app/user_login.html'


class UserLogoutView(LogoutView):
    template_name = 'blog_app/user_logout.html'

templates/blog_app/blog_app_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'list' %}">My Blog</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'blog_app:create' %}">New Post</a></li>
                <li><a class="navbar-link" href="#">Hola, {{ user.username }}</a></li>
                <li><a class="navbar-link" href="{% url 'blog_app:logout' %}">Logout</a></li>
                {% else %}
                <li><a class="navbar-link" href="{% url 'blog_app:login' %}">Login</a></li>
                <li><a class="navbar-link" href="{% url 'blog_app:register' %}">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="jumbotron">
            {% block body_block %}

            {% endblock %}
        </div>
    </div>
</body>

</html>

templates/blog_app/comment_create.html
{% extends 'blog_app/blog_app_base.html' %}

{% block body_block %}

{% if user.is_authenticated %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Submit">
</form>
{% else %}
<h1>You must login to comment!</h1>
{% endif %}
{% endblock %}

templates/blog_app/post_create.html
{% extends 'blog_app/blog_app_base.html' %}

{% block body_block %}

{% if user.is_authenticated %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Submit">
</form>
{% else %}
<h1>You must login to post!</h1>
{% endif %}
{% endblock %}

templates/blog_app/post_delete.html
{% extends 'blog_app/blog_app_base.html' %}

{% block body_block %}

{% if user.is_authenticated and user == post.user %}
<h1>Are you sure you want to delete?</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Submit">
    <a class="btn btn-primary" href="{% url 'blog_app:detail' pk=post.pk %}">Cancel</a>
</form>
{% else %}
<h1>You must login to delete your post!</h1>
{% endif %}
{% endblock %}

templates/blog_app/post_detail.html
{% extends 'blog_app/blog_app_base.html' %}

{% block body_block %}

<h1>{{ post_detail.title }}</h1>
<p>Published on: {{ post_detail.date_published }} by {{ post_detail.user.username }}</p>
<h2>{{ post_detail.post_content }}</h2>
{% if user == post_detail.user %}
<a class="btn btn-primary" href="{% url 'blog_app:update' pk=post_detail.pk %}">Update</a>
<a class="btn btn-primary" href="{% url 'blog_app:delete' pk=post_detail.pk %}">Delete</a>
{% endif %}
<h3>Comments:</h3>
{% for comment in post_detail.comments.all %}

<p>{{ comment.user.username }}: {{ comment.comment_content }}</p>

{% endfor %}
{% if user.is_authenticated %}

<a class="btn btn-primary" href="{% url 'blog_app:comment' pk=post_detail.pk %}">New Comment</a>

{% endif %}

{% endblock %}

templates/blog_app/post_list.html
{% extends 'blog_app/blog_app_base.html' %}

{% block body_block %}
{% if not posts %}
<h1>There are no posts available!</h1>
{% else %}
{% for post in posts %}
<h1><a href="{% url 'blog_app:detail' pk=post.pk %}">{{ post.title }}</a></h1>
<p>Published on: {{ post.date_published }} by {{ post.user.username }}</p>
<p><a href="{% url 'blog_app:comment' pk=post.pk %}">Comments: {{ post.comments.all.count }}</a></p>
{% if user == post.user %}
<a class="btn btn-primary" href="{% url 'blog_app:update' pk=post.pk %}">Update</a>
<a class="btn btn-primary" href="{% url 'blog_app:delete' pk=post.pk %}">Delete</a>
{% endif %}
{% endfor %}
{% endif %}
{% endblock %}

templates/blog_app/post_update.html
{% extends 'blog_app/blog_app_base.html' %}

{% block body_block %}

{% if user.is_authenticated and user == post.user %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Submit">
</form>
{% else %}
<h1>You must login to update your post!</h1>
{% endif %}
{% endblock %}

templates/blog_app/user_login.html
{% extends 'blog_app/blog_app_base.html' %}

{% block body_block %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-warning" value="Submit">

</form>

{% endblock %}

templates/blog_app/user_logout.html
{% extends 'blog_app/blog_app_base.html' %}

{% block body_block %}

<h1>Vuelve pronto!</h1>

{% endblock %}

templates/blog_app/user_registration.html
{% extends 'blog_app/blog_app_base.html' %}

{% block body_block %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-warning" value="Submit">

</form>

{% endblock %}